// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/alexbsec/AustralianChess/backend/internal/contracts (interfaces: Command)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	chess "github.com/alexbsec/AustralianChess/backend/internal/chess"
	contracts "github.com/alexbsec/AustralianChess/backend/internal/contracts"
	gomock "github.com/golang/mock/gomock"
)

// MockCommand is a mock of Command interface.
type MockCommand struct {
	ctrl     *gomock.Controller
	recorder *MockCommandMockRecorder
}

// MockCommandMockRecorder is the mock recorder for MockCommand.
type MockCommandMockRecorder struct {
	mock *MockCommand
}

// NewMockCommand creates a new mock instance.
func NewMockCommand(ctrl *gomock.Controller) *MockCommand {
	mock := &MockCommand{ctrl: ctrl}
	mock.recorder = &MockCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommand) EXPECT() *MockCommandMockRecorder {
	return m.recorder
}

// GetRoomId mocks base method.
func (m *MockCommand) GetRoomId() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomId")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetRoomId indicates an expected call of GetRoomId.
func (mr *MockCommandMockRecorder) GetRoomId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomId", reflect.TypeOf((*MockCommand)(nil).GetRoomId))
}

// SetColor mocks base method.
func (m *MockCommand) SetColor(arg0 chess.PieceColor) contracts.Command {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetColor", arg0)
	ret0, _ := ret[0].(contracts.Command)
	return ret0
}

// SetColor indicates an expected call of SetColor.
func (mr *MockCommandMockRecorder) SetColor(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetColor", reflect.TypeOf((*MockCommand)(nil).SetColor), arg0)
}

// SetPlayerId mocks base method.
func (m *MockCommand) SetPlayerId(arg0 string) contracts.Command {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPlayerId", arg0)
	ret0, _ := ret[0].(contracts.Command)
	return ret0
}

// SetPlayerId indicates an expected call of SetPlayerId.
func (mr *MockCommandMockRecorder) SetPlayerId(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPlayerId", reflect.TypeOf((*MockCommand)(nil).SetPlayerId), arg0)
}
