// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/alexbsec/AustralianChess/backend/internal/game (interfaces: Game)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	chess "github.com/alexbsec/AustralianChess/backend/internal/chess"
	bot "github.com/alexbsec/AustralianChess/backend/internal/chess/bot"
	contracts "github.com/alexbsec/AustralianChess/backend/internal/contracts"
	wsTypes "github.com/alexbsec/AustralianChess/backend/internal/ws/ws_types"
	gomock "github.com/golang/mock/gomock"
)

// MockGame is a mock of Game interface.
type MockGame struct {
	ctrl     *gomock.Controller
	recorder *MockGameMockRecorder
}

// MockGameMockRecorder is the mock recorder for MockGame.
type MockGameMockRecorder struct {
	mock *MockGame
}

// NewMockGame creates a new mock instance.
func NewMockGame(ctrl *gomock.Controller) *MockGame {
	mock := &MockGame{ctrl: ctrl}
	mock.recorder = &MockGameMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGame) EXPECT() *MockGameMockRecorder {
	return m.recorder
}

// HandlePlayBotRoom mocks base method.
func (m *MockGame) HandlePlayBotRoom(arg0 context.Context, arg1 string, arg2 chess.PieceColor, arg3 bot.Difficulty) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandlePlayBotRoom", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandlePlayBotRoom indicates an expected call of HandlePlayBotRoom.
func (mr *MockGameMockRecorder) HandlePlayBotRoom(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandlePlayBotRoom", reflect.TypeOf((*MockGame)(nil).HandlePlayBotRoom), arg0, arg1, arg2, arg3)
}

// HandleConnect mocks base method.
func (m *MockGame) HandleConnect(arg0 context.Context, arg1 string, arg2 *wsTypes.Client) (contracts.Result, chess.GameState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleConnect", arg0, arg1, arg2)
	ret0, _ := ret[0].(contracts.Result)
	ret1, _ := ret[1].(chess.GameState)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// HandleConnect indicates an expected call of HandleConnect.
func (mr *MockGameMockRecorder) HandleConnect(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleConnect", reflect.TypeOf((*MockGame)(nil).HandleConnect), arg0, arg1, arg2)
}

// HandleCommand mocks base method.
func (m *MockGame) HandleCommand(arg0 context.Context, arg1 string, arg2 *wsTypes.Client, arg3 contracts.Command) (contracts.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleCommand", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(contracts.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleCommand indicates an expected call of HandleCommand.
func (mr *MockGameMockRecorder) HandleCommand(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleCommand", reflect.TypeOf((*MockGame)(nil).HandleCommand), arg0, arg1, arg2, arg3)
}

// HandleDisconnect mocks base method.
func (m *MockGame) HandleDisconnect(arg0 string, arg1 *wsTypes.Client) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleDisconnect", arg0, arg1)
}

// HandleDisconnect indicates an expected call of HandleDisconnect.
func (mr *MockGameMockRecorder) HandleDisconnect(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleDisconnect", reflect.TypeOf((*MockGame)(nil).HandleDisconnect), arg0, arg1)
}

// HandleDestroyRoom mocks base method.
func (m *MockGame) HandleDestroyRoom(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleDestroyRoom", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleDestroyRoom indicates an expected call of HandleDestroyRoom.
func (mr *MockGameMockRecorder) HandleDestroyRoom(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleDestroyRoom", reflect.TypeOf((*MockGame)(nil).HandleDestroyRoom), arg0, arg1)
}
