// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/alexbsec/AustralianChess/backend/internal/chess/engine (interfaces: Engine)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	chess "github.com/alexbsec/AustralianChess/backend/internal/chess"
	engine "github.com/alexbsec/AustralianChess/backend/internal/chess/engine"
	gomock "github.com/golang/mock/gomock"
)

// MockEngine is a mock of Engine interface.
type MockEngine struct {
	ctrl     *gomock.Controller
	recorder *MockEngineMockRecorder
}

// MockEngineMockRecorder is the mock recorder for MockEngine.
type MockEngineMockRecorder struct {
	mock *MockEngine
}

// NewMockEngine creates a new mock instance.
func NewMockEngine(ctrl *gomock.Controller) *MockEngine {
	mock := &MockEngine{ctrl: ctrl}
	mock.recorder = &MockEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEngine) EXPECT() *MockEngineMockRecorder {
	return m.recorder
}

// GameResult mocks base method.
func (m *MockEngine) GameResult(arg0 *chess.GameState, arg1 chess.PieceColor) *chess.GameResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GameResult", arg0, arg1)
	ret0, _ := ret[0].(*chess.GameResult)
	return ret0
}

// GameResult indicates an expected call of GameResult.
func (mr *MockEngineMockRecorder) GameResult(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GameResult", reflect.TypeOf((*MockEngine)(nil).GameResult), arg0, arg1)
}

// PromotePawn mocks base method.
func (m *MockEngine) PromotePawn(arg0 *chess.GameState, arg1 chess.PieceColor, arg2 chess.PieceKind, arg3, arg4 chess.Position) engine.ValidationResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PromotePawn", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(engine.ValidationResponse)
	return ret0
}

// PromotePawn indicates an expected call of PromotePawn.
func (mr *MockEngineMockRecorder) PromotePawn(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PromotePawn", reflect.TypeOf((*MockEngine)(nil).PromotePawn), arg0, arg1, arg2, arg3, arg4)
}

// ValidateAndMove mocks base method.
func (m *MockEngine) ValidateAndMove(arg0 *chess.GameState, arg1 chess.PieceColor, arg2, arg3 chess.Position) engine.ValidationResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAndMove", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(engine.ValidationResponse)
	return ret0
}

// ValidateAndMove indicates an expected call of ValidateAndMove.
func (mr *MockEngineMockRecorder) ValidateAndMove(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAndMove", reflect.TypeOf((*MockEngine)(nil).ValidateAndMove), arg0, arg1, arg2, arg3)
}
