// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/alexbsec/AustralianChess/backend/internal/chess/engine (interfaces: Arbiter)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	chess "github.com/alexbsec/AustralianChess/backend/internal/chess"
	gomock "github.com/golang/mock/gomock"
)

// MockArbiter is a mock of Arbiter interface.
type MockArbiter struct {
	ctrl     *gomock.Controller
	recorder *MockArbiterMockRecorder
}

// MockArbiterMockRecorder is the mock recorder for MockArbiter.
type MockArbiterMockRecorder struct {
	mock *MockArbiter
}

// NewMockArbiter creates a new mock instance.
func NewMockArbiter(ctrl *gomock.Controller) *MockArbiter {
	mock := &MockArbiter{ctrl: ctrl}
	mock.recorder = &MockArbiterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArbiter) EXPECT() *MockArbiterMockRecorder {
	return m.recorder
}

// CanMovePiece mocks base method.
func (m *MockArbiter) CanMovePiece(arg0 chess.Board, arg1 chess.Piece, arg2, arg3 chess.Position) (bool, string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanMovePiece", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(string)
	return ret0, ret1
}

// CanMovePiece indicates an expected call of CanMovePiece.
func (mr *MockArbiterMockRecorder) CanMovePiece(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanMovePiece", reflect.TypeOf((*MockArbiter)(nil).CanMovePiece), arg0, arg1, arg2, arg3)
}

// IsCheckmate mocks base method.
func (m *MockArbiter) IsCheckmate(arg0 chess.Board, arg1 chess.PieceColor) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCheckmate", arg0, arg1)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsCheckmate indicates an expected call of IsCheckmate.
func (mr *MockArbiterMockRecorder) IsCheckmate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCheckmate", reflect.TypeOf((*MockArbiter)(nil).IsCheckmate), arg0, arg1)
}

// IsInCheck mocks base method.
func (m *MockArbiter) IsInCheck(arg0 chess.Board, arg1 chess.PieceColor) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsInCheck", arg0, arg1)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsInCheck indicates an expected call of IsInCheck.
func (mr *MockArbiterMockRecorder) IsInCheck(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsInCheck", reflect.TypeOf((*MockArbiter)(nil).IsInCheck), arg0, arg1)
}

// IsStalemate mocks base method.
func (m *MockArbiter) IsStalemate(arg0 chess.Board, arg1 chess.PieceColor) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsStalemate", arg0, arg1)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsStalemate indicates an expected call of IsStalemate.
func (mr *MockArbiterMockRecorder) IsStalemate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsStalemate", reflect.TypeOf((*MockArbiter)(nil).IsStalemate), arg0, arg1)
}
