// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/alexbsec/AustralianChess/backend/internal/ws (interfaces: IHandler)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	ws "github.com/alexbsec/AustralianChess/backend/internal/ws"
	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockIHandler is a mock of IHandler interface.
type MockIHandler struct {
	ctrl     *gomock.Controller
	recorder *MockIHandlerMockRecorder
}

// MockIHandlerMockRecorder is the mock recorder for MockIHandler.
type MockIHandlerMockRecorder struct {
	mock *MockIHandler
}

// NewMockIHandler creates a new mock instance.
func NewMockIHandler(ctrl *gomock.Controller) *MockIHandler {
	mock := &MockIHandler{ctrl: ctrl}
	mock.recorder = &MockIHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIHandler) EXPECT() *MockIHandlerMockRecorder {
	return m.recorder
}

// HandleRoom mocks base method.
func (m *MockIHandler) HandleRoom(arg0 *gin.Context, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleRoom", arg0, arg1)
}

// HandleRoom indicates an expected call of HandleRoom.
func (mr *MockIHandlerMockRecorder) HandleRoom(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleRoom", reflect.TypeOf((*MockIHandler)(nil).HandleRoom), arg0, arg1)
}

// PlayBot mocks base method.
func (m *MockIHandler) PlayBot(arg0 *gin.Context, arg1 ws.PlayBotDTO) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PlayBot", arg0, arg1)
}

// PlayBot indicates an expected call of PlayBot.
func (mr *MockIHandlerMockRecorder) PlayBot(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlayBot", reflect.TypeOf((*MockIHandler)(nil).PlayBot), arg0, arg1)
}
