// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/alexbsec/AustralianChess/backend/internal/ws (interfaces: IHub)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	chess "github.com/alexbsec/AustralianChess/backend/internal/chess"
	ws_types "github.com/alexbsec/AustralianChess/backend/internal/ws/ws_types"
	gomock "github.com/golang/mock/gomock"
)

// MockIHub is a mock of IHub interface.
type MockIHub struct {
	ctrl     *gomock.Controller
	recorder *MockIHubMockRecorder
}

// MockIHubMockRecorder is the mock recorder for MockIHub.
type MockIHubMockRecorder struct {
	mock *MockIHub
}

// NewMockIHub creates a new mock instance.
func NewMockIHub(ctrl *gomock.Controller) *MockIHub {
	mock := &MockIHub{ctrl: ctrl}
	mock.recorder = &MockIHubMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIHub) EXPECT() *MockIHubMockRecorder {
	return m.recorder
}

// AddBot mocks base method.
func (m *MockIHub) AddBot(arg0, arg1 string, arg2 chess.PieceColor) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddBot", arg0, arg1, arg2)
}

// AddBot indicates an expected call of AddBot.
func (mr *MockIHubMockRecorder) AddBot(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBot", reflect.TypeOf((*MockIHub)(nil).AddBot), arg0, arg1, arg2)
}

// AddClient mocks base method.
func (m *MockIHub) AddClient(arg0, arg1 string, arg2 ws_types.Conn) (*ws_types.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddClient", arg0, arg1, arg2)
	ret0, _ := ret[0].(*ws_types.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddClient indicates an expected call of AddClient.
func (mr *MockIHubMockRecorder) AddClient(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddClient", reflect.TypeOf((*MockIHub)(nil).AddClient), arg0, arg1, arg2)
}

// Broadcast mocks base method.
func (m *MockIHub) Broadcast(arg0 string, arg1 interface{}, arg2 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Broadcast", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Broadcast indicates an expected call of Broadcast.
func (mr *MockIHubMockRecorder) Broadcast(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Broadcast", reflect.TypeOf((*MockIHub)(nil).Broadcast), arg0, arg1, arg2)
}

// GetRoomForTest mocks base method.
func (m *MockIHub) GetRoomForTest(arg0 string) *ws_types.RoomClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomForTest", arg0)
	ret0, _ := ret[0].(*ws_types.RoomClient)
	return ret0
}

// GetRoomForTest indicates an expected call of GetRoomForTest.
func (mr *MockIHubMockRecorder) GetRoomForTest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomForTest", reflect.TypeOf((*MockIHub)(nil).GetRoomForTest), arg0)
}

// RemoveClient mocks base method.
func (m *MockIHub) RemoveClient(arg0 string, arg1 ws_types.Conn) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveClient", arg0, arg1)
}

// RemoveClient indicates an expected call of RemoveClient.
func (mr *MockIHubMockRecorder) RemoveClient(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveClient", reflect.TypeOf((*MockIHub)(nil).RemoveClient), arg0, arg1)
}

// SetOnRoomEmptyCallback mocks base method.
func (m *MockIHub) SetOnRoomEmptyCallback(arg0 func(string)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetOnRoomEmptyCallback", arg0)
}

// SetOnRoomEmptyCallback indicates an expected call of SetOnRoomEmptyCallback.
func (mr *MockIHubMockRecorder) SetOnRoomEmptyCallback(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOnRoomEmptyCallback", reflect.TypeOf((*MockIHub)(nil).SetOnRoomEmptyCallback), arg0)
}

// SetRoomForTest mocks base method.
func (m *MockIHub) SetRoomForTest(arg0 string, arg1 *ws_types.RoomClient) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRoomForTest", arg0, arg1)
}

// SetRoomForTest indicates an expected call of SetRoomForTest.
func (mr *MockIHubMockRecorder) SetRoomForTest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRoomForTest", reflect.TypeOf((*MockIHub)(nil).SetRoomForTest), arg0, arg1)
}

// StartJanitor mocks base method.
func (m *MockIHub) StartJanitor() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartJanitor")
}

// StartJanitor indicates an expected call of StartJanitor.
func (mr *MockIHubMockRecorder) StartJanitor() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartJanitor", reflect.TypeOf((*MockIHub)(nil).StartJanitor))
}
