// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/alexbsec/AustralianChess/backend/internal/ws/parser (interfaces: IParser)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	contracts "github.com/alexbsec/AustralianChess/backend/internal/contracts"
	gomock "github.com/golang/mock/gomock"
)

// MockIParser is a mock of IParser interface.
type MockIParser struct {
	ctrl     *gomock.Controller
	recorder *MockIParserMockRecorder
}

// MockIParserMockRecorder is the mock recorder for MockIParser.
type MockIParserMockRecorder struct {
	mock *MockIParser
}

// NewMockIParser creates a new mock instance.
func NewMockIParser(ctrl *gomock.Controller) *MockIParser {
	mock := &MockIParser{ctrl: ctrl}
	mock.recorder = &MockIParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIParser) EXPECT() *MockIParserMockRecorder {
	return m.recorder
}

// ParseMessage mocks base method.
func (m *MockIParser) ParseMessage(arg0 string, arg1 []byte) (contracts.Command, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseMessage", arg0, arg1)
	ret0, _ := ret[0].(contracts.Command)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseMessage indicates an expected call of ParseMessage.
func (mr *MockIParserMockRecorder) ParseMessage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseMessage", reflect.TypeOf((*MockIParser)(nil).ParseMessage), arg0, arg1)
}
