// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/alexbsec/AustralianChess/backend/internal/auth (interfaces: IAuthorizer)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	http "net/http"
	reflect "reflect"

	sessions "github.com/alexbsec/AustralianChess/backend/sessions"
	gomock "github.com/golang/mock/gomock"
)

// MockIAuthorizer is a mock of IAuthorizer interface.
type MockIAuthorizer struct {
	ctrl     *gomock.Controller
	recorder *MockIAuthorizerMockRecorder
}

// MockIAuthorizerMockRecorder is the mock recorder for MockIAuthorizer.
type MockIAuthorizerMockRecorder struct {
	mock *MockIAuthorizer
}

// NewMockIAuthorizer creates a new mock instance.
func NewMockIAuthorizer(ctrl *gomock.Controller) *MockIAuthorizer {
	mock := &MockIAuthorizer{ctrl: ctrl}
	mock.recorder = &MockIAuthorizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAuthorizer) EXPECT() *MockIAuthorizerMockRecorder {
	return m.recorder
}

// Authorize mocks base method.
func (m *MockIAuthorizer) Authorize(arg0 context.Context, arg1 *http.Request) (*sessions.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authorize", arg0, arg1)
	ret0, _ := ret[0].(*sessions.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authorize indicates an expected call of Authorize.
func (mr *MockIAuthorizerMockRecorder) Authorize(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authorize", reflect.TypeOf((*MockIAuthorizer)(nil).Authorize), arg0, arg1)
}
