// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/alexbsec/AustralianChess/backend/rooms (interfaces: IService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	chess "github.com/alexbsec/AustralianChess/backend/internal/chess"
	contracts "github.com/alexbsec/AustralianChess/backend/internal/contracts"
	rooms "github.com/alexbsec/AustralianChess/backend/rooms"
	gomock "github.com/golang/mock/gomock"
)

// MockIService is a mock of IService interface.
type MockIService struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceMockRecorder
}

// MockIServiceMockRecorder is the mock recorder for MockIService.
type MockIServiceMockRecorder struct {
	mock *MockIService
}

// NewMockIService creates a new mock instance.
func NewMockIService(ctrl *gomock.Controller) *MockIService {
	mock := &MockIService{ctrl: ctrl}
	mock.recorder = &MockIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIService) EXPECT() *MockIServiceMockRecorder {
	return m.recorder
}

// CreateRoom mocks base method.
func (m *MockIService) CreateRoom(arg0 context.Context) (rooms.CreateRoomResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoom", arg0)
	ret0, _ := ret[0].(rooms.CreateRoomResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRoom indicates an expected call of CreateRoom.
func (mr *MockIServiceMockRecorder) CreateRoom(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoom", reflect.TypeOf((*MockIService)(nil).CreateRoom), arg0)
}

// DeleteRoom mocks base method.
func (m *MockIService) DeleteRoom(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRoom", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRoom indicates an expected call of DeleteRoom.
func (mr *MockIServiceMockRecorder) DeleteRoom(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRoom", reflect.TypeOf((*MockIService)(nil).DeleteRoom), arg0, arg1)
}

// DisplayRoom mocks base method.
func (m *MockIService) DisplayRoom(arg0 context.Context, arg1 string) (rooms.DisplayRoomResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisplayRoom", arg0, arg1)
	ret0, _ := ret[0].(rooms.DisplayRoomResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DisplayRoom indicates an expected call of DisplayRoom.
func (mr *MockIServiceMockRecorder) DisplayRoom(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisplayRoom", reflect.TypeOf((*MockIService)(nil).DisplayRoom), arg0, arg1)
}

// ExecuteCommand mocks base method.
func (m *MockIService) ExecuteCommand(arg0 context.Context, arg1 contracts.Command) (contracts.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteCommand", arg0, arg1)
	ret0, _ := ret[0].(contracts.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteCommand indicates an expected call of ExecuteCommand.
func (mr *MockIServiceMockRecorder) ExecuteCommand(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteCommand", reflect.TypeOf((*MockIService)(nil).ExecuteCommand), arg0, arg1)
}

// FetchRoom mocks base method.
func (m *MockIService) FetchRoom(arg0 context.Context, arg1 string) (*rooms.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchRoom", arg0, arg1)
	ret0, _ := ret[0].(*rooms.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchRoom indicates an expected call of FetchRoom.
func (mr *MockIServiceMockRecorder) FetchRoom(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchRoom", reflect.TypeOf((*MockIService)(nil).FetchRoom), arg0, arg1)
}

// UpdatePlayerJoined mocks base method.
func (m *MockIService) UpdatePlayerJoined(arg0 context.Context, arg1, arg2 string, arg3 chess.PieceColor) (contracts.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlayerJoined", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(contracts.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePlayerJoined indicates an expected call of UpdatePlayerJoined.
func (mr *MockIServiceMockRecorder) UpdatePlayerJoined(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlayerJoined", reflect.TypeOf((*MockIService)(nil).UpdatePlayerJoined), arg0, arg1, arg2, arg3)
}
