name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    defaults:
      run:
        working-directory: ./backend   

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Install deps
        run: go mod download

      - name: Install go-test-coverage
        run: go install github.com/vladopajic/go-test-coverage/v2@latest

      - name: Build
        run: go build ./...

      - name: Run tests
        run: go test ./... -covermode=atomic -coverprofile=cover.out

      - name: Check coverage
        run: $(go env GOPATH)/bin/go-test-coverage --config=./.testcoverage.yml

      - name: Show coverage total
        run: go tool cover -func=cover.out | grep total

      - name: Login to GHCR
        working-directory: .
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        working-directory: .
        run: |
          IMAGE=ghcr.io/${{ github.repository }}:latest
          docker build -t $IMAGE .

      - name: Push Docker image
        working-directory: .
        run: |
          IMAGE=ghcr.io/${{ github.repository }}:latest
          docker push $IMAGE
