name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    defaults:
      run:
        working-directory: ./backend   

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Install deps
        run: go mod download

      - name: Run tests (exclude mocks)
        run: |
          PKGS=$(go list ./... | grep -v /mocks/)

          TEST_PKGS=""

          for pkg in $PKGS; do
            if go test -c $pkg >/dev/null 2>&1; then
              TEST_PKGS="$TEST_PKGS $pkg"
            fi
          done

          go test $TEST_PKGS -covermode=atomic -coverprofile=coverage.out

      - name: Check coverage threshold
        run: |
          total=$(go tool cover -func=coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
          echo "Total coverage: $total%"

          threshold=80.0

          awk -v total="$total" -v threshold="$threshold" 'BEGIN {
            if (total < threshold) {
              printf("Coverage %.2f%% is below threshold %.2f%%\n", total, threshold)
              exit 1
            } else {
              printf("Coverage OK: %.2f%% >= %.2f%%\n", total, threshold)
            }
          }'

      - name: Login to GHCR
        working-directory: .
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        working-directory: .
        run: |
          IMAGE=ghcr.io/${{ github.repository }}:latest
          docker build -t $IMAGE .

      - name: Push Docker image
        working-directory: .
        run: |
          IMAGE=ghcr.io/${{ github.repository }}:latest
          docker push $IMAGE
